---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent
#       state: latest

  - name: add php support for php
    apt:
      name: libapache2-mod-php
      state: absent
